### ISSUE TITLE
Comparison to github.com/alexedwards/scs

### ISSUE THREAD

**Issue by Xeoncross** [abraithwaite/jeff#14]
A quick look at both libraries seems to show an important difference: github.com/alexedwards/scs buffers all response bytes. A `bufferedResponseWriter{}` buffering all output to catch session changes before headers are sent (

- https://github.com/alexedwards/scs/blob/master/session.go#L118
- Which at one point [supported websockets by implementing hijack?](https://github.com/alexedwards/scs/pull/12).

Jeff seems to handle this better (but not easier) by making you call [Set](https://github.com/abraithwaite/jeff/blob/master/sessions.go#L174) manually when headers should be set without [wrapping your http.Handler](https://github.com/abraithwaite/jeff/blob/master/sessions.go#L143).

Don't use alexedwards/scs if you send large payloads to clients, stream response bodies, use websockets(?), etc.

**Comment by abraithwaite** [comment]
Yeah, that's weird.  I've got no idea why he's using a buffered response writer.  I guess it's for transparently handling setting the cookie?  This looks pretty rough too:

https://github.com/alexedwards/scs/blob/efc4b6b318277be948e5fc6eb5c218a1f160f090/session.go#L137

Maybe I can write a bit more of an in-depth comparison of the two.  His was definitely the strongest contender when I was looking around for a library.

**Comment by alexedwards** [comment]
>  I've got no idea why he's using a buffered response writer. I guess it's for transparently handling setting the cookie?

Yep, that's right. The `LoadAndSave()` middleware in SCS is basically a helper for the common scenario where you want to communicate the session token (or *session id*) to the client in a cookie. One of the things it does is add the cookie to the `Set-Cookie` response header, if necessary, as the middleware chain is unwound.

If the `ResponseWriter` write wasn't buffered by this middleware, when a handler calls `w.WriteHeader()` --- either explicitly, or implicitly via `w.Write()` --- the response headers would be written *before* the middleware was able to add the `Set-Cookie` header. And the session token would never make it back to the client.

One of the big design decisions I made with v2 of SCS was to make the saving of session data and communication of the session token to the client independent processes. It makes the package a lot more flexible, as people can write their own middleware to communicate the session token in other ways if they want to (like in a JSON body, or in an `X-Session` header).

Well done on the jeff package, it's good to see some more alternatives to gorilla sessions :+1:

**Comment by abraithwaite** [comment]
Thanks for the discussion here guys!  Closing this out for now. :-)
