### ISSUE TITLE
sessions: Clear doesn't return potential error

### ISSUE THREAD

**Issue by yanniszark** [abraithwaite/jeff#21]
Clear function in sessions.go doesn't handle the return value of the clear function.

https://github.com/abraithwaite/jeff/blob/a6a878dbd405856816ca5bd5b0899346b8ff8f5a/sessions.go#L225

**Comment by abraithwaite** [comment]
Great point!  Do you think the preference would be to simply add an error return value to the signature of the function?

Technically I think that should backwards compatible, but it might throw a few vet errors for some users.

**Comment by yanniszark** [comment]
@abraithwaite I believe that changing the signature of an exported function breaks compatibility.
Thanks for catching that!

I see two possible solutions:
1) Break compatibility and bump the major version.
2) Introduce another function, with the correct functionality.

**Comment by abraithwaite** [comment]
I don't think breaking compatibility is completely out of the question here.  It's certainly not a major breaking change and would likely not result in builds failing for most users.  Furthermore, I haven't tagged this as 1.0.0 yet, so minor breaking changes are definitely not outside the realm of possibility. :-)

**Comment by abraithwaite** [comment]
Fixed in #25
