### ISSUE TITLE
sessions: load all sessions for user

### ISSUE THREAD

**Issue by yanniszark** [abraithwaite/jeff#22]
Hi @abraithwaite!
First of all, I want to say thanks a lot for this package, I found out that popular packages were lacking for my use-case where I want to search sessions by user-id.

However, after taking a look around, I couldn't find an exported function to get all active sessions for a user.
This is helpful, for example, if the user is logged in from many devices and we want to revoke them all at once.

Thoughts?

**Comment by abraithwaite** [comment]
This definitely makes sense.  If you want to instrument your app to be able to clear all sessions for an individual user that seems like the only way to do it short of building your own tooling to interact with your store.

I'll add it!

**Comment by abraithwaite** [comment]
I went ahead and implemented this, however I would like to note that if you wish to revoke _all_ active sessions for a single user, it's only necessary to delete their key in the store.

However, I still believe this is a useful method to have to build tooling with, despite leaking some details about how we're storing them on the backend.
